name: Staging Tests
on: [workflow_dispatch]
jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        include:

          - test-name: ubuntu-22.04-python-3.9
            os: ubuntu-22.04
            python-version: "3.9"

          - test-name: ubuntu-22.04-python-3.10
            os: ubuntu-22.04
            python-version: "3.10"

          - test-name: ubuntu-22.04-python-3.11
            os: ubuntu-22.04
            python-version: "3.11"

          - test-name: ubuntu-24.04-python-3.12
            os: ubuntu-24.04
            python-version: "3.12"

          - test-name: ubuntu-24.04-python-3.13
            os: ubuntu-24.04
            python-version: "3.13"

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r tests/requirements.txt

      - name: Mount staging.gethttpsforfree.com on local for serving challenge files
        env:
          STAGING_SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
        run: |
          sudo apt install sshfs
          export SSHFS_KEYFILE=$(pwd)/sshfs_key.pem
          touch $SSHFS_KEYFILE
          chmod 600 $SSHFS_KEYFILE
          echo "$STAGING_SSH_KEY" > $SSHFS_KEYFILE
          mkdir -p /tmp/challenge-files
          nohup sshfs -o StrictHostKeyChecking=no,debug,IdentityFile=$SSHFS_KEYFILE -p 2299 challengeuser@staging.gethttpsforfree.com:/acme-challenge /tmp/challenge-files &
          sleep 10
          ls -lah /tmp/challenge-files

      - name: Run tests using the Let's Encrypt staging server
        run: |
          export ACME_TINY_USE_STAGING="1"
          export ACME_TINY_DOMAIN="staging.gethttpsforfree.com"
          export ACME_TINY_SSHFS_CHALLENGE_DIR="/tmp/challenge-files"
          coverage run --source . --omit ./setup.py -m unittest tests

      - name: Print coverage report
        run: coverage report -m

